costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 2
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/speed_filter_mask"
    base: 0.45
    multiplier: -0.002857
filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/speed_filter_mask"
    yaml_filename: "/home/hazem/GolfCar_ws/src/golfcar_control/maps/speed_limit_mask.yaml"
